---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque       # default for arbitary key-value pairs
data:
  mongodb-root-username: bWFuZ29kYg==
  mongodb-root-password: bWFuZ29kYg==

  # here storing secret directly is not recommended, use encrypted text instead.
  # $ echo -n "mongodb" | base64  
  #  bWFuZ29kYg==

  # Deploy Secret before Deploymentfile, since Deploymentfile looks for Secret values which
  # should be deployed in k8s cluster already.
